### ISSUE TITLE
The requested nginx plugin does not appear to be installed

### ISSUE THREAD

**Issue by mzhadigerov** [dylanjcastillo/fastapi-nginx-gunicorn#4]
I'm getting warning when I do `sudo certbot --nginx`

```
The requested nginx plugin does not appear to be installed
```

at this step of the tutorial:

https://dylancastillo.co/fastapi-nginx-gunicorn/#:~:text=sudo%20certbot%20%2D%2Dnginx

**Comment by dylanjcastillo** [comment]
I don't think you'd be able to run certbot if the port 80 isn't available: https://community.letsencrypt.org/t/certbot-letsencrypt-on-different-port-than-443/173632/19

Not sure how to solve that tbh.

Also, you probably have an older version of certbot, so you need to remove first and then reinstall.

**Comment by mzhadigerov** [comment]
@dylanjcastillo My port 80 is available, but I have another application on my server (apache2, which was developed by other people). My initial goal going through all that was to make my app to be able to work on `https`

![image](https://user-images.githubusercontent.com/55549813/231825415-34f8b483-420c-4505-9865-e785d8974caf.png)
